# Generated by Django 5.1 on 2025-06-04 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_alter_member_address_alter_member_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='qr_code',
            field=models.ImageField(blank=True, default=2, upload_to='qr_codes/'),
            preserve_default=False,
        ),
    ]
