# Generated by Django 5.1 on 2025-06-04 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_alter_member_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='qr_code',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
