# Generated by Django 5.1 on 2025-08-12 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_alter_member_qr_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='program_of_study',
            new_name='specialization',
        ),
        migrations.RemoveField(
            model_name='member',
            name='level_of_study',
        ),
        migrations.RemoveField(
            model_name='member',
            name='membership_class',
        ),
        migrations.AddField(
            model_name='member',
            name='level_of_profession',
            field=models.CharField(choices=[('NSP', 'NSP'), ('JA', 'JA'), ('Associate', 'Associate'), ('Expert', 'Expert')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='attendancesetting',
            name='attendance_type',
            field=models.CharField(choices=[('working_hours', 'Working Hours'), ('event', 'Event'), ('small_group', 'Small Group')], max_length=20),
        ),
        migrations.AlterField(
            model_name='member',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10),
        ),
    ]
