# Generated by Django 5.1 on 2025-08-21 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_rename_program_of_study_member_specialization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancesetting',
            name='attendance_type',
            field=models.CharField(choices=[('working_hours', 'Working Hours'), ('event', 'Event')], max_length=20),
        ),
    ]
